### PR TITLE
Initial sample of chatGPT plugin

### PR DESCRIPTION
**Pull request by jeromeof**
Hi, just some sample code to get you started if you are interested in plugin the spinorama data into chatgpt via a plugin

### CODE REVIEW

**Comment by pierreaubert** [comment]
Thanks I will have a look. It opens interesting ideas.

**Comment by jeromeof** [comment]
> Thanks I will have a look. It opens interesting ideas.

Yes, IMO it mainly depends on how good the chatGPT generation of useful notebook "steps" for audio analysis might be.  I don't know yet - I have just experimented in the past few weeks with lots of prompt engineering techniques (forcing ChatGPT to generate more useful 'code' ) and when I spotted that one of the plugin is basically a Python "Notebook" (except with the Python bit hidden) it seems that people who experiment a bit more with spinorama analysis themselves might have the opportunity if the raw data was made availalle easily via a "plugin" API.

So, I didn't look too deeply at your codebase - but I did see lots of python (so I am guessing you are familiar with libraries like fastapi ) - but I can develop this for you if you are interested. Obviously what I pushed there won't work without a bit of work within the "API" implementation and I did think the API might need a few more parameters beyond just the speaker name.

Anyway, I think these are interesting times

**Comment by pierreaubert** [comment]
I created a basic API

[https://api.spinorama.org/](https://api.spinorama.org/)

based on your proposition. You can push / contribute but please on the dev branch first. I am committing some files now.

**Comment by jeromeof** [comment]
Brillant - looks great - I will try it out this week - I am still waiting for full chatgpt-plugin access - I saw someone created a limited way of running the plugin-api on a 'local' alpaca LLM (really mini self-hosted chatGPT) - so If I don't get the proper access this week I will spin that up and see if I can use this API.  

Though I don't think that version will include a 'notebook' capability (which is really where I see the potential for these plugin-api - i.e. allow people who are not data-scientistic and python devs to interact and visualise the raw data in whatever way they can 'describe')

If I see anything to change, I will push to this dev branch

**Comment by pierreaubert** [comment]
I open a discussion for the format of the API

[here](https://github.com/pierreaubert/spinorama/discussions/237#discussion-5046356)

**Comment by pierreaubert** [comment]
They changed the format / idea of plugins. I need to adapt to the new API.

**Comment by jeromeof** [comment]
Yes, sorry about wasting your time last year on this API before. This stuff is so 'bleeding edge' that it does change. 
 I am currently investigating "GPTs" for my day job but given how quickly things change I decided it probably wasn't worth contacting you about it. I also spent some time investigating using "RAG" which is a technique to lookup external 'private' graph databases and 'indexed' documents to pull relevant information into the 'prompt'.  With that technique you would effectively index your spinorama Data for fast lookups

**Pull request closed without merging**
